### PR TITLE
Optimization

### PR DESCRIPTION
**Pull request by leongold**

### CODE REVIEW

**Comment by leongold** [comment]
Is this alright?

**Comment by EdDev** [comment]
You can squash the two commits and push with --force
You just need the last one.

**Comment by EdDev** [comment]
No idea why we can't just see the diff between this branch and master: https://github.com/leongold/linked_list/pull/2/files?diff=unified

I was expecting to see the two files added, not a diff in them.

**Comment by leongold** [comment]
I have never squashed before, do I just rebase and set the previous commits as "squash" with the last one as "pick"?

**Comment by EdDev** [comment]
You just do: git reabse -i HEAD~3

And mark which commits should be squashed to the previous commit:
pick d47ffad blabla
squash d3a290f blabla2
squash d3a290f blabla3

This squashes the last two into the first.

**Comment by leongold** [comment]
I might have messed something up in the process, but even now if I attempt to create a new pull request (master is definitely empty)  in the "files changed" it compares commits between optimization and optimization

**Pull request closed without merging**
